/** core 统一出口：宿主（win GUI / linux CLI）从这里取全部引擎能力 */
export { setPlatform, getPlatform, hasPlatform, type Platform, type ProxyConfig } from './platform'
export * from './types'
export { loadSettings, saveSettings, loadTokens, saveTokens, clearTokens, type StoredTokens } from './settings'
export { logger } from './logger'
export { netClient, isTransientNetError } from './net/NetClient'
export { workerTemplate } from './net/workerTemplate'
export { authService } from './auth/AuthService'
export { driveClient, ApiError, FOLDER_MIME } from './drive/DriveClient'
export { transferEngine } from './transfer/TransferEngine'
export { UploadTask } from './transfer/UploadTask'
export { DownloadTask } from './transfer/DownloadTask'
export { TaskStore } from './transfer/taskStore'
export { backupManager } from './backup/BackupManager'
export { BackupStore, type StoredBackup } from './backup/BackupStore'
export * as diskCache from './storage/DiskCache'
export { updateService, updateCacheDir, updateCacheFiles } from './update/UpdateService'
